// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TournamentPlannerDbLib;

namespace TournamentPlannerDbLib.Migrations
{
    [DbContext(typeof(TournamentContext))]
    partial class TournamentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TournamentPlannerDbLib.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Person1Id")
                        .HasColumnType("int");

                    b.Property<int?>("Person2Id")
                        .HasColumnType("int");

                    b.Property<int>("Round")
                        .HasColumnType("int");

                    b.Property<int?>("WinnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Person1Id");

                    b.HasIndex("Person2Id");

                    b.HasIndex("WinnerId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("TournamentPlannerDbLib.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Firstname = "Violet",
                            Gender = "Female",
                            Lastname = "Landor"
                        },
                        new
                        {
                            Id = 2,
                            Firstname = "Levi",
                            Gender = "Female",
                            Lastname = "Humbatch"
                        },
                        new
                        {
                            Id = 3,
                            Firstname = "Myrtice",
                            Gender = "Female",
                            Lastname = "Weinham"
                        },
                        new
                        {
                            Id = 4,
                            Firstname = "Elaine",
                            Gender = "Female",
                            Lastname = "Rastall"
                        },
                        new
                        {
                            Id = 5,
                            Firstname = "Marc",
                            Gender = "Male",
                            Lastname = "Clashe"
                        },
                        new
                        {
                            Id = 6,
                            Firstname = "Leena",
                            Gender = "Female",
                            Lastname = "Cheetham"
                        },
                        new
                        {
                            Id = 7,
                            Firstname = "Ennis",
                            Gender = "Male",
                            Lastname = "Bottlestone"
                        },
                        new
                        {
                            Id = 8,
                            Firstname = "Lester",
                            Gender = "Female",
                            Lastname = "Palatino"
                        },
                        new
                        {
                            Id = 9,
                            Firstname = "Margareta",
                            Gender = "Male",
                            Lastname = "Feasey"
                        },
                        new
                        {
                            Id = 10,
                            Firstname = "Pavlov",
                            Gender = "Male",
                            Lastname = "Stealfox"
                        },
                        new
                        {
                            Id = 11,
                            Firstname = "Brinna",
                            Gender = "Male",
                            Lastname = "Le feuvre"
                        },
                        new
                        {
                            Id = 12,
                            Firstname = "Karlie",
                            Gender = "Female",
                            Lastname = "Iskow"
                        },
                        new
                        {
                            Id = 13,
                            Firstname = "Albert",
                            Gender = "Male",
                            Lastname = "Syncke"
                        },
                        new
                        {
                            Id = 14,
                            Firstname = "Luella",
                            Gender = "Female",
                            Lastname = "Foat"
                        },
                        new
                        {
                            Id = 15,
                            Firstname = "Curtice",
                            Gender = "Male",
                            Lastname = "Pepper"
                        },
                        new
                        {
                            Id = 16,
                            Firstname = "Kendell",
                            Gender = "Female",
                            Lastname = "Dawber"
                        },
                        new
                        {
                            Id = 17,
                            Firstname = "Imogen",
                            Gender = "Female",
                            Lastname = "MacDuff"
                        },
                        new
                        {
                            Id = 18,
                            Firstname = "Hunfredo",
                            Gender = "Male",
                            Lastname = "Stanyon"
                        },
                        new
                        {
                            Id = 19,
                            Firstname = "Maurizio",
                            Gender = "Female",
                            Lastname = "Tapscott"
                        },
                        new
                        {
                            Id = 20,
                            Firstname = "Norris",
                            Gender = "Male",
                            Lastname = "Demkowicz"
                        },
                        new
                        {
                            Id = 21,
                            Firstname = "Zacharia",
                            Gender = "Male",
                            Lastname = "Brundall"
                        },
                        new
                        {
                            Id = 22,
                            Firstname = "Stephani",
                            Gender = "Female",
                            Lastname = "Beecraft"
                        },
                        new
                        {
                            Id = 23,
                            Firstname = "Mervin",
                            Gender = "Male",
                            Lastname = "Sondon"
                        },
                        new
                        {
                            Id = 24,
                            Firstname = "Leena",
                            Gender = "Female",
                            Lastname = "Divisek"
                        },
                        new
                        {
                            Id = 25,
                            Firstname = "Goran",
                            Gender = "Female",
                            Lastname = "Henric"
                        },
                        new
                        {
                            Id = 26,
                            Firstname = "Othilie",
                            Gender = "Female",
                            Lastname = "Knight"
                        },
                        new
                        {
                            Id = 27,
                            Firstname = "Morena",
                            Gender = "Male",
                            Lastname = "Mault"
                        },
                        new
                        {
                            Id = 28,
                            Firstname = "Corina",
                            Gender = "Male",
                            Lastname = "Simmens"
                        },
                        new
                        {
                            Id = 29,
                            Firstname = "Roanna",
                            Gender = "Male",
                            Lastname = "Caulfield"
                        },
                        new
                        {
                            Id = 30,
                            Firstname = "Berenice",
                            Gender = "Female",
                            Lastname = "Sturzaker"
                        },
                        new
                        {
                            Id = 31,
                            Firstname = "Raynard",
                            Gender = "Male",
                            Lastname = "Leport"
                        },
                        new
                        {
                            Id = 32,
                            Firstname = "Xerxes",
                            Gender = "Male",
                            Lastname = "Sully"
                        });
                });

            modelBuilder.Entity("TournamentPlannerDbLib.Match", b =>
                {
                    b.HasOne("TournamentPlannerDbLib.Person", "Person1")
                        .WithMany()
                        .HasForeignKey("Person1Id");

                    b.HasOne("TournamentPlannerDbLib.Person", "Person2")
                        .WithMany()
                        .HasForeignKey("Person2Id");

                    b.HasOne("TournamentPlannerDbLib.Person", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId");

                    b.Navigation("Person1");

                    b.Navigation("Person2");

                    b.Navigation("Winner");
                });
#pragma warning restore 612, 618
        }
    }
}
